# Generated by Django 6.0.5 on 2026-05-20 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_text', models.TextField()),
                ('detected_barangay', models.CharField(blank=True, max_length=100, null=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('disaster_type', models.CharField(choices=[('flooding', 'Flooding'), ('storm', 'Storm'), ('landslide', 'Landslide'), ('tree_damage', 'Tree Damage'), ('fire', 'Fire'), ('earthquake', 'Earthquake'), ('unknown', 'Unknown')], default='flooding', max_length=20)),
                ('confidence', models.FloatField(default=0.0)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('matched_entities', models.JSONField(blank=True, default=list)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
    ]
