# Generated by Django 6.0.2 on 2026-05-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='disaster_type',
            field=models.CharField(choices=[('flooding', 'Flooding'), ('storm', 'Storm')], default='flooding', max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
