# Generated by Django 6.0.2 on 2026-05-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0002_alter_report_disaster_type_alter_report_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='disaster_type',
            field=models.CharField(choices=[('flooding', 'Flooding'), ('storm', 'Storm'), ('landslide', 'Landslide'), ('tree_damage', 'Tree Damage'), ('fire', 'Fire'), ('earthquake', 'Earthquake'), ('unknown', 'Unknown')], default='flooding', max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
