# Generated by Django 6.0.2 on 2026-05-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0003_alter_report_disaster_type_alter_report_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='disaster_type',
            field=models.CharField(choices=[('flooding', 'Flooding'), ('storm', 'Storm')], default='flooding', max_length=20),
        ),
    ]
